# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               Comic Firsts
tagline:             'Multiple Firsts for Comics'
description:         'First appearances of key comic book figures along with notes and other important information.'
url:                 http://comicfirsts.com
baseurl:             http://comicfirsts.com
paginate:            20

# About/contact
author:
  name:              Brian Plunkett
  url:               https://linkedin.com/briandplunkett
  email:             brian.plunkett@gmail.com

# Custom vars
version:             1.0.0
