# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Comic Firsts
tagline:             'Multiple Firsts for Comics'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://comicfirsts.com
baseurl:             http://comicfirsts.com
paginate:            5

# About/contact
author:
  name:              Brian Plunkett
  url:               https://linked.com/briandplunkett
  email:             brian.plunkett@gmail.com

# Custom vars
version:             1.0.0
